jenkins:
  controller:
    containerSecurityContext:
      allowPrivilegeEscalation: true
    admin:
      password: "Devl@1234"
    additionalPlugins:
      - job-dsl
      - docker-workflow
  agent:
    additionalContainers:
      - sideContainerName: docker
        image:
          repository: docker
          tag: dind
        privileged: true
        args: ""
    envVars:
      - name: DOCKER_HOST
        value: "unix:///var/run/docker.sock"