jenkins:
  controller:
    containerSecurityContext:
      allowPrivilegeEscalation: true
    admin:
      password: "Devl@1234"
    additionalPlugins:
      - job-dsl
      - docker-workflow
    sidecars:
      additionalSidecarContainers:
        - name: dind
          image: docker:dind-rootless
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: /var/user/1000/docker.sock
    containerEnv:
      - name: DOCKER_HOST
        value: "tcp://localhost:2375"
  agent:
    volumes:
      - type: EmptyDir
        mountPath: /var/user/1000/docker.sock
    additionalContainers:
      - sideContainerName: docker
        image:
          repository: docker
          tag: dind-rootless
        privileged: true
        args: ""
  persistence:
    volumes:
      - name: dockersock
        emptyDir: {}