jenkins:
  controller:
    containerSecurityContext:
      allowPrivilegeEscalation: true
    admin:
      password: "Devl@1234"
    additionalPlugins:
      - job-dsl
      - docker-workflow
    containerEnv:
      - name: DOCKER_HOST
        value: "tcp://localhost:2376"
  agent:
    additionalContainers:
      - sideContainerName: docker
        image:
          repository: docker
          tag: dind
        privileged: true
        args: ""
    envVars:
      - name: DOCKER_HOST
        value: "unix:///var/user/1000/docker.sock"